name: Test

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run linting with ruff
        run: |
          uv run ruff check memory_mcp_server/
          uv run ruff format --check memory_mcp_server/

      # - name: Run type checking with mypy
      #   run: uv run mypy memory_mcp_server/

      - name: Run unit tests
        run: uv run pytest tests/ -k "not integration" --cov=memory_mcp_server --cov-report=xml --cov-report=term-missing -v

      - name: Run integration tests
        run: uv run pytest tests/ -k "integration" -v
        env:
          # Add any environment variables needed for integration tests
          DATABASE_URL: sqlite:///test_integration.db

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
